apiVersion: apps/v1
kind: Deployment
metadata:
  name: tristaprogrammista-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tristaprogrammista-bot  # This label should match the template labels below
  template:
    metadata:
      labels:
        app: tristaprogrammista-bot  # This label should match the selector above
    spec:
      containers:
        - name: tristaprogrammista-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ecr-secret